---
name: Deploy to GitHub Pages

on:
  push:
    branches:
      # Main branch deployment
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history
          fetch-depth: 0
          # Ensure credentials are available for subsequent Git operations
          persist-credentials: true

      - name: Diagnostic information
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Ref Name: ${{ github.ref_name }}"

      - name: Update base href in index.html
        run: |
          # Update the base href in index.html with the correct root path
          sed -i 's|<base href="/">|<base href="/UltimatePiTrainer/">|g' index.html
          echo "Updated base href to /UltimatePiTrainer/"
          # Verify the change
          grep "<base href" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true

      - name: Log deployment result
        run: |
          echo "Deployment completed to https://anthonykazyaka.github.io/UltimatePiTrainer/"
